name: release
on:
  push:
    tags:
      - 'v*'  # This will trigger on tags starting with 'v', e.g., 'v1.0.0'
  workflow_dispatch:  # Enable manual triggering of the workflow
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Get major, minor and patch version
        if: startsWith(github.ref, 'refs/tags/')
        id: build
        run: |
          # Remove the 'v' prefix and split the version string into components
          version="${GITHUB_REF#refs/tags/v}"
          echo "Version: $version"
          # Extract major, minor, and patch versions
          IFS='.' read -r major minor patch <<< "$version"
          # Output the results
          echo "Major version: $major"
          echo "Minor version: $minor"
          echo "Patch version: $patch"
          # Set these as environment variables
          echo "MAJOR_VERSION=$major" >> $GITHUB_ENV
          echo "MINOR_VERSION=$minor" >> $GITHUB_ENV
          echo "PATCH_VERSION=$patch" >> $GITHUB_ENV
  build:
    needs: setup
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # Lint with pylint
      - name: Lint with pylint
        run: |
          pylint csv2b64img.py
      # Test with pytest
      - name: Test with pytest
        run: |
          pytest testcsv2b64img.py
      # Write version file
      - name: Write version file
        run: |
          (Get-Content "$GITHUB_WORKSPACE/version-file.txt") -replace '\$([A-Z_]+)', { Get-Item env:\$matches[1] } | Set-Content "$RUNNER_TEMP/version-file.txt"
      # Build executable
      - name: Build with pyinstaller
        run: |
          pyinstaller --onefile csv2b64img.py --version-file="$RUNNER_TEMP/version-file.txt"
      # Compress executable
      - name: compress executable
        run: |
          Compress-Archive -Path "./dist/csv2b64img.exe" -DestinationPath "./dist/csv2b64img.zip"
      # Generate SHA256 checksum
      - name: Generate SHA256 checksum
        run: |
          Get-FileHash "./dist/csv2b64img.zip" -Algorithm SHA256 | ForEach-Object { $_.Hash } | Out-File -FilePath "./dist/csv2b64img.zip.sha256sum"
          echo "SHA_WIN64_ZIP=$(Get-Content ./dist/csv2b64img.zip.sha256sum)" >> $GITHUB_ENV
      # Create release notes
      - name: Create release notes
        id: release_note
        run: |
          (Get-Content "$GITHUB_WORKSPACE/version-file.txt") -replace '\$([A-Z_]+)', { Get-Item env:\$matches[1] } | Set-Content "$RUNNER_TEMP/version-file.txt"
          cat "$RUNNER_TEMP/RELEASE_NOTE"
        outputs:
          note: $RUNNER_TEMP/RELEASE_NOTE
      # Create a release on GitHub
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: ${{ steps.release_note.outputs.note }}
          draft: false
          prerelease: false
      # Upload compiled assets or package to the release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/csv2b64img.zip  # Adjust to the path of your build artifact
          asset_name: "csv2b64img.zip"  # Name of the uploaded asset
          asset_content_type: application/zip